-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public."Autobuses"
(
    id_autobus character varying NOT NULL,
    nombre character varying NOT NULL,
    matricula character varying NOT NULL,
    "nº_serie" integer NOT NULL,
    PRIMARY KEY (id_autobus)
);

CREATE TABLE IF NOT EXISTS public."Lugares"
(
    id_lugar character varying NOT NULL,
    nombre character varying NOT NULL,
    provincia character varying NOT NULL,
    distancia integer NOT NULL,
    PRIMARY KEY (id_lugar)
);

CREATE TABLE IF NOT EXISTS public."Conductores"
(
    id_conductor character varying NOT NULL,
    nombre character varying NOT NULL,
    dni character varying NOT NULL,
    PRIMARY KEY (id_conductor)
);

CREATE TABLE IF NOT EXISTS public."Lugares-Conductores-Autobuses"
(
    id_ruta serial NOT NULL,
    fecha integer NOT NULL,
    id_lugar character varying NOT NULL,
    id_autobus character varying NOT NULL,
    id_conductor character varying NOT NULL,
    PRIMARY KEY (id_ruta)
);

ALTER TABLE IF EXISTS public."Lugares-Conductores-Autobuses"
    ADD CONSTRAINT id_lugar FOREIGN KEY (id_lugar)
    REFERENCES public."Lugares" (id_lugar) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."Lugares-Conductores-Autobuses"
    ADD CONSTRAINT id_autobus FOREIGN KEY (id_autobus)
    REFERENCES public."Autobuses" (id_autobus) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."Lugares-Conductores-Autobuses"
    ADD CONSTRAINT id_conductor FOREIGN KEY (id_conductor)
    REFERENCES public."Conductores" (id_conductor) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

END;